// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: secrets.proto

package secrets

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SecretsManagementClient is the client API for SecretsManagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SecretsManagementClient interface {
	AddCredentials(ctx context.Context, in *Password, opts ...grpc.CallOption) (*Response, error)
	AddCardInfo(ctx context.Context, in *CardInfo, opts ...grpc.CallOption) (*Response, error)
	AddTextInfo(ctx context.Context, in *TextInfo, opts ...grpc.CallOption) (*Response, error)
	ListSecrets(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*ListSecretResponse, error)
}

type secretsManagementClient struct {
	cc grpc.ClientConnInterface
}

func NewSecretsManagementClient(cc grpc.ClientConnInterface) SecretsManagementClient {
	return &secretsManagementClient{cc}
}

func (c *secretsManagementClient) AddCredentials(ctx context.Context, in *Password, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.SecretsManagement/AddCredentials", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsManagementClient) AddCardInfo(ctx context.Context, in *CardInfo, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.SecretsManagement/AddCardInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsManagementClient) AddTextInfo(ctx context.Context, in *TextInfo, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.SecretsManagement/AddTextInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsManagementClient) ListSecrets(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*ListSecretResponse, error) {
	out := new(ListSecretResponse)
	err := c.cc.Invoke(ctx, "/proto.SecretsManagement/ListSecrets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecretsManagementServer is the server API for SecretsManagement service.
// All implementations must embed UnimplementedSecretsManagementServer
// for forward compatibility
type SecretsManagementServer interface {
	AddCredentials(context.Context, *Password) (*Response, error)
	AddCardInfo(context.Context, *CardInfo) (*Response, error)
	AddTextInfo(context.Context, *TextInfo) (*Response, error)
	ListSecrets(context.Context, *EmptyRequest) (*ListSecretResponse, error)
	mustEmbedUnimplementedSecretsManagementServer()
}

// UnimplementedSecretsManagementServer must be embedded to have forward compatible implementations.
type UnimplementedSecretsManagementServer struct {
}

func (UnimplementedSecretsManagementServer) AddCredentials(context.Context, *Password) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCredentials not implemented")
}
func (UnimplementedSecretsManagementServer) AddCardInfo(context.Context, *CardInfo) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCardInfo not implemented")
}
func (UnimplementedSecretsManagementServer) AddTextInfo(context.Context, *TextInfo) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTextInfo not implemented")
}
func (UnimplementedSecretsManagementServer) ListSecrets(context.Context, *EmptyRequest) (*ListSecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSecrets not implemented")
}
func (UnimplementedSecretsManagementServer) mustEmbedUnimplementedSecretsManagementServer() {}

// UnsafeSecretsManagementServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SecretsManagementServer will
// result in compilation errors.
type UnsafeSecretsManagementServer interface {
	mustEmbedUnimplementedSecretsManagementServer()
}

func RegisterSecretsManagementServer(s grpc.ServiceRegistrar, srv SecretsManagementServer) {
	s.RegisterService(&SecretsManagement_ServiceDesc, srv)
}

func _SecretsManagement_AddCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Password)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsManagementServer).AddCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SecretsManagement/AddCredentials",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsManagementServer).AddCredentials(ctx, req.(*Password))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsManagement_AddCardInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CardInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsManagementServer).AddCardInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SecretsManagement/AddCardInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsManagementServer).AddCardInfo(ctx, req.(*CardInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsManagement_AddTextInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsManagementServer).AddTextInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SecretsManagement/AddTextInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsManagementServer).AddTextInfo(ctx, req.(*TextInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsManagement_ListSecrets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsManagementServer).ListSecrets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SecretsManagement/ListSecrets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsManagementServer).ListSecrets(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SecretsManagement_ServiceDesc is the grpc.ServiceDesc for SecretsManagement service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SecretsManagement_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SecretsManagement",
	HandlerType: (*SecretsManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddCredentials",
			Handler:    _SecretsManagement_AddCredentials_Handler,
		},
		{
			MethodName: "AddCardInfo",
			Handler:    _SecretsManagement_AddCardInfo_Handler,
		},
		{
			MethodName: "AddTextInfo",
			Handler:    _SecretsManagement_AddTextInfo_Handler,
		},
		{
			MethodName: "ListSecrets",
			Handler:    _SecretsManagement_ListSecrets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "secrets.proto",
}
