// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Nymfeparakit/gophkeeper/client/internal/services (interfaces: ItemCryptoService)

// Package mock_services is a generated GoMock package.
package mock_services

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockItemCryptoService is a mock of ItemCryptoService interface.
type MockItemCryptoService struct {
	ctrl     *gomock.Controller
	recorder *MockItemCryptoServiceMockRecorder
}

// MockItemCryptoServiceMockRecorder is the mock recorder for MockItemCryptoService.
type MockItemCryptoServiceMockRecorder struct {
	mock *MockItemCryptoService
}

// NewMockItemCryptoService creates a new mock instance.
func NewMockItemCryptoService(ctrl *gomock.Controller) *MockItemCryptoService {
	mock := &MockItemCryptoService{ctrl: ctrl}
	mock.recorder = &MockItemCryptoServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockItemCryptoService) EXPECT() *MockItemCryptoServiceMockRecorder {
	return m.recorder
}

// DecryptItem mocks base method.
func (m *MockItemCryptoService) DecryptItem(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecryptItem", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DecryptItem indicates an expected call of DecryptItem.
func (mr *MockItemCryptoServiceMockRecorder) DecryptItem(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecryptItem", reflect.TypeOf((*MockItemCryptoService)(nil).DecryptItem), arg0)
}

// EncryptItem mocks base method.
func (m *MockItemCryptoService) EncryptItem(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncryptItem", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// EncryptItem indicates an expected call of EncryptItem.
func (mr *MockItemCryptoServiceMockRecorder) EncryptItem(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncryptItem", reflect.TypeOf((*MockItemCryptoService)(nil).EncryptItem), arg0)
}
