// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Nymfeparakit/gophkeeper/client/internal/services (interfaces: UpdateDeleteBinaryService)

// Package mock_services is a generated GoMock package.
package mock_services

import (
	context "context"
	reflect "reflect"

	dto "github.com/Nymfeparakit/gophkeeper/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockUpdateDeleteBinaryService is a mock of UpdateDeleteBinaryService interface.
type MockUpdateDeleteBinaryService struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateDeleteBinaryServiceMockRecorder
}

// MockUpdateDeleteBinaryServiceMockRecorder is the mock recorder for MockUpdateDeleteBinaryService.
type MockUpdateDeleteBinaryServiceMockRecorder struct {
	mock *MockUpdateDeleteBinaryService
}

// NewMockUpdateDeleteBinaryService creates a new mock instance.
func NewMockUpdateDeleteBinaryService(ctrl *gomock.Controller) *MockUpdateDeleteBinaryService {
	mock := &MockUpdateDeleteBinaryService{ctrl: ctrl}
	mock.recorder = &MockUpdateDeleteBinaryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateDeleteBinaryService) EXPECT() *MockUpdateDeleteBinaryServiceMockRecorder {
	return m.recorder
}

// DeleteLocalSecret mocks base method.
func (m *MockUpdateDeleteBinaryService) DeleteLocalSecret(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLocalSecret", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLocalSecret indicates an expected call of DeleteLocalSecret.
func (mr *MockUpdateDeleteBinaryServiceMockRecorder) DeleteLocalSecret(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLocalSecret", reflect.TypeOf((*MockUpdateDeleteBinaryService)(nil).DeleteLocalSecret), arg0, arg1)
}

// DeleteRemoteSecret mocks base method.
func (m *MockUpdateDeleteBinaryService) DeleteRemoteSecret(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRemoteSecret", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRemoteSecret indicates an expected call of DeleteRemoteSecret.
func (mr *MockUpdateDeleteBinaryServiceMockRecorder) DeleteRemoteSecret(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRemoteSecret", reflect.TypeOf((*MockUpdateDeleteBinaryService)(nil).DeleteRemoteSecret), arg0, arg1)
}

// UpdateLocalSecret mocks base method.
func (m *MockUpdateDeleteBinaryService) UpdateLocalSecret(arg0 context.Context, arg1 dto.BinaryInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLocalSecret", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLocalSecret indicates an expected call of UpdateLocalSecret.
func (mr *MockUpdateDeleteBinaryServiceMockRecorder) UpdateLocalSecret(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLocalSecret", reflect.TypeOf((*MockUpdateDeleteBinaryService)(nil).UpdateLocalSecret), arg0, arg1)
}

// UpdateRemoteSecret mocks base method.
func (m *MockUpdateDeleteBinaryService) UpdateRemoteSecret(arg0 context.Context, arg1 dto.BinaryInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRemoteSecret", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRemoteSecret indicates an expected call of UpdateRemoteSecret.
func (mr *MockUpdateDeleteBinaryServiceMockRecorder) UpdateRemoteSecret(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRemoteSecret", reflect.TypeOf((*MockUpdateDeleteBinaryService)(nil).UpdateRemoteSecret), arg0, arg1)
}
